### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sahil1786**
Docs Updated

---
name: PR
about: Pull Request
title: ''
labels: ''
assignees: dextel2

---

### What have you Changed(must)

Write here what you have changed in codebase

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder.
- [ ] I am following clean code and Documentation.
- [ ] I have added title and what program will do first in the file.
- [ ] I have not tampred with the database key or any other modules

### CODE REVIEW

**Review by dextel2 — CHANGES_REQUESTED** [review]
The change set looks like there is nothing beside FOSSA links. Could you please add details about the
- Controllers
- Models ? Thanks

**Comment by Sahil1786** [comment]
Can you describe please about the Controllers

Models ??

**Comment by dextel2** [comment]
@Sahil1786  I strongly suggest to go through the code in here

image

https://github.com/dextel2/core-server/tree/master/controllers
https://github.com/dextel2/core-server/tree/master/models

**Comment by Sahil1786** [comment]
Controls like - how to use something ?? Actually I didn't understand that's why. I am asking you .this my first time I am continuing in documentation .

**Comment by dextel2** [comment]
You need to understand what are controller/models/view or in other words MVC structure. Here's a starting point in reference to this project https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes

**Review by dextel2 — CHANGES_REQUESTED** [review]
Update the readme in such a way that it reflects the contents and the way project works!

**Pull request closed without merging**
